# Generated by Django 2.0.5 on 2018-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'instituição', 'verbose_name_plural': 'instituições'},
        ),
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'série', 'verbose_name_plural': 'séries'},
        ),
        migrations.RemoveField(
            model_name='componente',
            name='organizacao',
        ),
        migrations.AlterField(
            model_name='ensino',
            name='nome',
            field=models.CharField(help_text='A etapa do ensino na educação em que a série está inserida, ex: Infantil, Fundamental, Médio, EJA', max_length=100),
        ),
    ]
