# Generated by Django 2.0.5 on 2018-05-31 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180530_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(help_text='Carga horária semanal do componente nas séries.', verbose_name='Carga horária')),
                ('componente', models.ForeignKey(help_text='Componente que irá compor a matriz curricular', on_delete=django.db.models.deletion.CASCADE, to='core.Componente')),
            ],
            options={
                'verbose_name': 'componente matriz',
                'verbose_name_plural': 'componentes matrizes',
            },
        ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1024)),
                ('organizacao', models.ForeignKey(help_text='A organização que essa instituição de ensino faz parte, ex: Prefeitura de São Judas', on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao')),
            ],
            options={
                'verbose_name': 'período letivo',
                'verbose_name_plural': 'períodos letivos',
            },
        ),
        migrations.AddField(
            model_name='componentematriz',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MatrizCurricular'),
        ),
        migrations.AddField(
            model_name='componentematriz',
            name='series',
            field=models.ManyToManyField(help_text='As série que esse componente contém a carga horária especificada.', to='core.Serie'),
        ),
    ]
