# Generated by Django 2.0.5 on 2018-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180531_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizcurricular',
            name='descricao',
            field=models.TextField(max_length=1024),
        ),
    ]
