# Generated by Django 2.0.5 on 2018-05-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180531_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrizcurricular',
            options={'verbose_name': 'matriz curricular', 'verbose_name_plural': 'matrizes curriculares'},
        ),
    ]
